In [1]:
import tensorflow as tf
import tensorflow_datasets as tfds

In [ ]:
dataset = tfds.load("crema_d")

In [7]:
len(dataset["train"])

5144

In [8]:
len(dataset["validation"])

738

In [9]:
len(dataset["test"])

1556

In [20]:
for sample in dataset["train"].take(3):
    print(sample)

{'audio': <tf.Tensor: shape=(40574,), dtype=int64, numpy=array([ -90,  -97, -111, ...,    0,    0,    0], dtype=int64)>, 'label': <tf.Tensor: shape=(), dtype=int64, numpy=3>, 'speaker_id': <tf.Tensor: shape=(), dtype=string, numpy=b'1056'>}
{'audio': <tf.Tensor: shape=(34701,), dtype=int64, numpy=array([-212, -221, -231, ...,    0,    0,   -1], dtype=int64)>, 'label': <tf.Tensor: shape=(), dtype=int64, numpy=1>, 'speaker_id': <tf.Tensor: shape=(), dtype=string, numpy=b'1028'>}
{'audio': <tf.Tensor: shape=(59793,), dtype=int64, numpy=array([382, 363, 379, ...,   0,   0,   0], dtype=int64)>, 'label': <tf.Tensor: shape=(), dtype=int64, numpy=2>, 'speaker_id': <tf.Tensor: shape=(), dtype=string, numpy=b'1007'>}
